### Numpy Basic

What is NumPy?

NumPy stands for Numerical Python. The NumPy library is the core library for scientific computing in Python.
It is used for:

Fast numerical calculations

Working with arrays

Data science, machine learning, scientific computing

Simple idea:

Python list = slow for math
NumPy array = fast & smart

Installing Numpy (Colab users: already installed)

pip install numpy #in vs code to install in terminal

In [2]:
import numpy as np

###Python List Vs Numpy Array

In [4]:
py_list = [1, 2, 3]
np_array = np.array([1, 2, 3])

print(py_list * 2)
print(np_array * 2) #np lekheysi balla real ans diyo

[1, 2, 3, 1, 2, 3]
[2 4 6]


###Speed comparision of operation on python list and numpy array

In [5]:
import time

list1 = list(range(1000000))
sum = 0

# Using python list
start_time = time.time()
for num in list1:
  sum += num
end_time = time.time()

print(f"Sum of list1: {sum}")
print(f"Time taken on python list: {end_time-start_time}")

Sum of list1: 499999500000
Time taken on python list: 0.11711406707763672


In [6]:
np_array = np.array(range(1000000))

# Using numpy array
start_time = time.time()
sum = np.sum(np_array)
end_time = time.time()

print(f"Sum of np_array: {sum}")
print(f"Time taken on numpy array: {end_time-start_time}")

Sum of np_array: 499999500000
Time taken on numpy array: 0.0012531280517578125


###Creating Numpy Array

1) From Python List

In [7]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
x = [1, 2, 3]
a = np.array(x)
print(a)

[1 2 3]


2) Zero array

In [9]:
x = np.zeros(5)
print(x) # default float

[0. 0. 0. 0. 0.]


In [14]:
x = input() #input vayesi auto string hunxa
print(type(x))

3.14
<class 'str'>


In [16]:
x=12/2
print(x)
print(type(x)) #float since there is use of division

6.0
<class 'float'>


In [18]:

np.zeros((3,4), dtype=np.int32) #3 rows 4 column

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

3) One Array

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

4) Using arrange()

In [21]:
np.arange(1, 10) # Like Python range() but returns an array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
r = range(1, 10)
print(r)  # range object

range(1, 10)


5) Using linspace()

In [26]:
np.linspace(2, 10, 5) # Evenly spaced values 2 10 vaneyko range anni 5 vaneyko 5 oota digit ma evenly spread

array([ 2.,  4.,  6.,  8., 10.])

6) Using logspace()

In [29]:
np.logspace(0, 3, num=4, base=10) #return number spaced evenly so on logscale

array([   1.,   10.,  100., 1000.])

7) Using full()

In [30]:
np.full((5,2), fill_value=2, dtype=np.int32) # Generating nd array with same value

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]], dtype=int32)

8) Using eye

In [31]:
np.eye(3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###NumPy Array Attributes

In [32]:
a = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.int64)

print(a)

[[1 2 3]
 [4 5 6]]


In [33]:
print(f"Data type (dtype):       {a.dtype}")
print(f"Shape (rows, cols):     {a.shape}")
print(f"Total elements (size):  {a.size}")
print(f"Number of dimensions:   {a.ndim}")
print(f"Bytes per item:         {a.itemsize} bytes")
print(f"Total memory (nbytes):  {a.nbytes} bytes")

Data type (dtype):       int64
Shape (rows, cols):     (2, 3)
Total elements (size):  6
Number of dimensions:   2
Bytes per item:         8 bytes
Total memory (nbytes):  48 bytes


In [34]:
#Array attributes:
arr1 = np.array([.2, .3, 4.8, .4, 77, 9.1])
print(arr1)
print(arr1.dtype)

[ 0.2  0.3  4.8  0.4 77.   9.1]
float64


In [35]:
arr2 = np.array([.2, .3, 4.8, .4, 77, 9.1], dtype=np.int64)
print(arr2)
print(arr2.dtype)

[ 0  0  4  0 77  9]
int64


In [36]:
arr = np.array([1, 2, 3])
print(arr.astype(np.float64)) # next way of converting data types

[1. 2. 3.]


In [37]:
# Reshaping Arrays
arr = np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [38]:
arr.shape

(16,)

In [39]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

###NumPy Arrays Dimensions with Indexing

1D array Indexing

In [40]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [41]:
print(x[0])   # first value
print(x[3])   # fourth value
print(x[-1])  # last value

1
4
5


2D Array Indexing

In [42]:
class_marks = np.array(
          [[40, 50, 60],
          [70, 80, 90],
          [55, 65, 75]])

print(class_marks)

[[40 50 60]
 [70 80 90]
 [55 65 75]]


Row 0 → [40, 50, 60]<br>
Row 1 → [70, 80, 90]<br>
Row 2 → [55, 65, 75]<br>
Indexing Format: array[row_index][column_index]

In [43]:
print(class_marks[0][0])  # Row 0, Column 0 → 40
print(class_marks[1][2])  # Row 1, Column 2 → 90
print(class_marks[2][1])  # Row 2, Column 1 → ?

40
90
65


3D indexing

In [44]:
school_marks = np.array(
              [[[40, 50],
                [60, 70],
                [50, 60]],

              [[80, 85],
               [90, 95],
               [90, 100]]])

print(school_marks)

[[[ 40  50]
  [ 60  70]
  [ 50  60]]

 [[ 80  85]
  [ 90  95]
  [ 90 100]]]


In [45]:
school_marks.shape

(2, 3, 2)

Class 0<br>
Student 0 → [40, 50]<br>
Student 1 → [60, 70]<br>
Student 2 → [50, 60]<br>
<br>
Class 1<br>
Student 0 → [80, 85]<br>
Student 1 → [90, 95]<br>
Student 2 → [90, 100]<br>
Indexing: array[class][row][column]

In [46]:
print(school_marks[0][0][1])  # Class 0, Student 0, Subject 1 → 50
print(school_marks[1][1][0])  # Class 1, Student 1, Subject 0 → 90

50
90


In [47]:
print(school_marks[1, 2, 1])  # Class 1, Student 2, Subject 1 → 100

100


###Randomness & Reproducibility

In [48]:
import random

In [53]:
np.random.seed(1337) # reproducibility

np.random.randint(1,10) # Random integer from [1, 10) #1 included and 10 not with that bracket sign #np leygarda random value ni yautai dekhauna milxa

8

In [59]:
num=np.random.randint(1,10)
guess= int((input("Guess a number between 1 and 10: ")))
if guess==num:
  print("You won!")
else:
  print("You lost!")
  display(num)

Guess a number between 1 and 10: 3
You lost!


'num'

###Different ways of creating random values

1) np.random.randint() → Random Integers

In [66]:
np.random.randint(1, 7) # single value: low (inclusive) → high (exclusive)

6

In [67]:
np.random.randint(0, 100, size=5) # 1D array

array([ 6, 22, 66, 75, 65])

In [68]:
np.random.randint(10, 50, size=(2,3)) # 2D array

array([[33, 29, 27],
       [37, 13, 30]])

2) np.random.rand() → Random Floats [0, 1)<br>

Used when:

.Probabilities <br>
.ML weights

In [69]:
np.random.rand()        # single value

0.7601717738058574

In [70]:
np.random.rand(5)       # 1D array

array([0.18780841, 0.28816715, 0.67021886, 0.49964826, 0.17856868])

In [71]:
np.random.rand(2, 3)    # 2D array

array([[0.4131413 , 0.19919524, 0.5316994 ],
       [0.8323707 , 0.18525095, 0.95735922]])

In [72]:
np.random.random((2, 3)) # same as rand() but takes only one argument for 2D

array([[0.42541467, 0.50400704, 0.51047095],
       [0.01579145, 0.73169007, 0.99330504]])

3) np.random.randn() → Random from Standard Normal Distribution
Mean 0, Std Dev 1.<br>
Values:

Can be negative

Mostly around 0

In [75]:
np.random.randn() #-3 to 3"

0.36701868900629514

In [76]:
np.random.randn(5)

array([ 1.11855474, -0.00838994,  0.46631538,  1.2632687 , -0.90165465])

In [77]:
np.random.randn(2, 3)

array([[-1.02884269,  0.56967842,  0.64166478],
       [ 0.25981193,  1.19317814, -1.04630036]])

4) np.random.shuffle() → Shuffle In-Place

In [78]:
arr = np.array([1,2,3,4,5])
print(arr)
np.random.shuffle(arr)
print(arr)

[1 2 3 4 5]
[3 1 2 5 4]


In [79]:
import numpy as np
import ipywidgets as widgets
from ipywidgets import interact

@interact(rows=(1,10), cols=(1,10))
def create_array(rows=3, cols=3):
    return np.random.randint(0, 100, size=(rows, cols))

interactive(children=(IntSlider(value=3, description='rows', max=10, min=1), IntSlider(value=3, description='c…

In [80]:
# Decorators: enhance the base function
import time

def timer(base_fn):
  def enhanced_fn():
    start_time = time.time()
    base_fn()
    stop_time = time.time()
    print(f"Time taken: {stop_time - start_time} seconds")
  return enhanced_fn

@timer
def brewtea():
  print("Making Tea")
  time.sleep(1)
  print("Tea is ready")

brewtea()

Making Tea
Tea is ready
Time taken: 1.0044937133789062 seconds
