<a href="https://colab.research.google.com/github/Aayushkassey/Machine_Learning_ml/blob/main/Numpy_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Slicing (1D, 2D, 3D)





In [1]:
import numpy as np

1D Array Slicing

array[start : end : step]

In [2]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)

[10 20 30 40 50 60]


Basic Slicing

In [3]:
arr[1:4]    # from index 1 to 3

array([20, 30, 40])

In [4]:
arr[:]

array([10, 20, 30, 40, 50, 60])

In [5]:

arr[:3]     # from start to index 2

array([10, 20, 30])

In [6]:
arr[3:]     # from index 3 to end

array([40, 50, 60])

In [7]:
arr[3:5]     # from index 3 to 4

array([40, 50])

Step Slicing

In [8]:
arr[::2]    # every second element

array([10, 30, 50])

In [9]:
arr[::3]    # every third element and first initial is auto selected

array([10, 40])

In [11]:
arr[::-1]    # reverse

array([60, 50, 40, 30, 20, 10])

2D Array Slicing

array[row_slice, column_slice]

In [12]:
mat = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(mat)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


Row Slicing

In [22]:
mat[0:2, :] #2 oota colon le array dimension preserve garxa vaney 1 colon le gardaina

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
mat[1:] #row one dekhi sabbai ho and Presented in 1 D

array([[40, 50, 60],
       [70, 80, 90]])

Column Slicing

In [24]:
mat[:, 0:2]

array([[10, 20],
       [40, 50],
       [70, 80]])

In [25]:
mat[:, 2] #2 column dekhi uuta and presented in 1D

array([30, 60, 90])

Specific Block

In [27]:
mat[0:2, 1:3]

array([[20, 30],
       [50, 60]])

3D Array Slicing

cube[class][row][column]

In [29]:
cube = np.array([
    [
        [10, 20, 30],
        [40, 50, 60]
    ],
    [
        [70, 80, 90],
        [100, 110, 120]
    ]
])
print(cube)


[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [31]:
print(cube.shape) #2by3 ko matrix 2 oota xa

(2, 2, 3)


Slice one entire class

In [33]:
cube[0, :, :]

array([[10, 20, 30],
       [40, 50, 60]])

In [34]:
cube[0:2, :, :]

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

Slice Specific Rows Across Classes

In [36]:
cube[:, 0, :]

array([[10, 20, 30],
       [70, 80, 90]])

Slice Specific Column

In [37]:
cube[:, :, 2]

array([[ 30,  60],
       [ 90, 120]])

Slice Specific Block

In [38]:
print(cube)
print("\n")
cube[0:2, 0:1, 1:2]

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]




array([[[20]],

       [[80]]])

# Question: select 50 and 110

In [42]:
cube[0:2, 1:2, 1:2] # array dimension preserve vayo tara cube[0:2, 1:2, 1] yeshle gardaina since only 2 colon

array([[[ 50]],

       [[110]]])

In [46]:
#50 and 80
cube[0:1, 1:2, 1:2], cube[1:2, 0:1, 1:2]

(array([[[50]]]), array([[[80]]]))

Fancy Indexing and Boolean Indexing

In [88]:
M = np.arange(12).reshape(3,4)
print("M:\n", M)
print('\n')
print("row 1:", M[1])
print('\n')
idx = [0,2]
print("row 0 and row 2:\n", M[idx]) # fancy indexing only in row

M:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


row 1: [4 5 6 7]


row 0 and row 2:
 [[ 0  1  2  3]
 [ 8  9 10 11]]


In [89]:
# Fancy Indexing
grid = np.array([['A', 'B', 'C'],
                 ['D', 'E', 'F'],
                 ['G', 'H', 'I']])

print("Original Grid:")
print(grid)

Original Grid:
[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]


In [90]:
# We want (0,0) which is 'A' and (2,2) which is 'I'
rows = [0, 2]
cols = [0, 2]

result = grid[rows, cols]
print(result)

['A' 'I']


In [91]:

# boolean indexing: select even numbers
x = np.arange(10)
print(x)
bool_x = (x % 2 == 0)
print(bool_x)
print("even numbers:", x[bool_x])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
even numbers: [0 2 4 6 8]


Array Operations

In [92]:
a = np.array([[1., 2., 3.],
              [4., 5., 6.]])

b = np.array([[1., 2., 3.],
              [7., 8., 9.]])

In [93]:
g= a - b
g

array([[ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [94]:
np.subtract(a, b)

array([[ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [95]:
g= a + b
g

array([[ 2.,  4.,  6.],
       [11., 13., 15.]])

In [96]:
np.add(a, b)

array([[ 2.,  4.,  6.],
       [11., 13., 15.]])

In [97]:
g= a * b
g

array([[ 1.,  4.,  9.],
       [28., 40., 54.]])

In [98]:
np.multiply(a, b)

array([[ 1.,  4.,  9.],
       [28., 40., 54.]])

In [99]:
np.divide(a, b) #a/b

array([[1.        , 1.        , 1.        ],
       [0.57142857, 0.625     , 0.66666667]])

In [100]:
np.exp(b) # Exponentiation (e^b) yeshma 2.710088676e+00 vaneyko e ko power kati vaneyko

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [101]:
np.sqrt(b) # square root of every element of b

array([[1.        , 1.41421356, 1.73205081],
       [2.64575131, 2.82842712, 3.        ]])

In [102]:
np.sqrt(a) # square root of every element of a

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [103]:
np.sin(b) # trigonometric function (in ?)

array([[0.84147098, 0.90929743, 0.14112001],
       [0.6569866 , 0.98935825, 0.41211849]])

In [104]:

np.log(b) # natural log (base = ?)

array([[0.        , 0.69314718, 1.09861229],
       [1.94591015, 2.07944154, 2.19722458]])

Matrix Multiplication

In [105]:
f = np.array([[1., 2.],
              [1., 3.]])
g = np.array([[1., 2.],
              [3., 4.]])
mul= f @ g  # @ ley hamro matrix wala multiplication garxa
print (mul)

[[ 7. 10.]
 [10. 14.]]


In [106]:
f = np.array([[1., 2.],
              [1., 3.]])
g = np.array([[1., 2.],
              [3., 4.]])

print(np.dot(f, g)) # mulitplies f * g

[[ 7. 10.]
 [10. 14.]]


Comparision Operators (Element-wise Comparision)

In [107]:
print(a)
print(b)
a == b

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [7. 8. 9.]]


array([[ True,  True,  True],
       [False, False, False]])

In [108]:
a < b

array([[False, False, False],
       [ True,  True,  True]])

Aggregate Functions

In [109]:
M = np.arange(1,13).reshape(3,4)  # 3x4
print("M:\n", M)
print("min:", M.min())
print("max:", M.max())
print("sum all:", M.sum())
# axis 0: first dimension, axis 1: second dimension and soon

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
min: 1
max: 12
sum all: 78


In [112]:
print("sum axis=0 (per column):", M.sum(axis=0)) # sabbai ko column sepeate plus garni

sum axis=0 (per column): [15 18 21 24]


In [117]:
print("sum axis=1 (per row):", M.sum(axis=1)) #axix 1 le row ma plus garni

sum axis=1 (per row): [10 26 42]


In [118]:
print("mean:", M.mean(), "std:", M.std())
# argmin and argmax return index of smallest and largest value, not the value itself
print("argmin axis=0 (per column):", M.argmin(axis=0))
print("argmax axis=1 (per row):", M.argmax(axis=1))

mean: 6.5 std: 3.452052529534663
argmin axis=0 (per column): [0 0 0 0]
argmax axis=1 (per row): [3 3 3]


In [125]:
np.random.shuffle(M)
print(M)
print("argmin axis=0 (per column):", M.argmin(axis=0)) # min index per column
print("argmax axis=1 (per row):", M.argmax(axis=1)) # max index per row

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
argmin axis=0 (per column): [2 2 2 2]
argmax axis=1 (per row): [3 3 3]


Broadcasting

NumPy automatically stretches smaller arrays so shapes match.

In [128]:
a = np.array([1, 2, 3])
b = 5  # scalar

result = a + b #array ma 5 plus gareyko
print(result)  # [6 7 8]

[6 7 8]


""" Broadcasting Rules:

Compare shapes from right to left.

Two dimensions are compatible if:

They are equal, OR

One of them is 1.

If incompatible, NumPy throws an error. """

In [129]:
a = np.array([[1], [2], [3]])
print(f"Matrix a: \n{a}")
print(np.shape(a))
print('\n')
# shape (3,1)


b = np.array([10, 20, 30])
print(f"Matrix b: \n{b}")
print(np.shape(b))
# shape (3,): treat as (1,3) for broadcasting

result = a + b
print("\n")
print(f"Result: \n{result}")
print(np.shape(result))
# shape(3,3)

Matrix a: 
[[1]
 [2]
 [3]]
(3, 1)


Matrix b: 
[10 20 30]
(3,)


Result: 
[[11 21 31]
 [12 22 32]
 [13 23 33]]
(3, 3)


In [132]:
a = np.array([[1,2,3],[4,5,6]])
print(f"Matrix a: \n{a}")
print(np.shape(a))
print("\n")

b = np.array([10, 20])
print(f"Matrix b: \n{b}")
print(np.shape(b))


result = a + b
print("\n")
print(f"Result: \n{result}")
print(np.shape(result))

Matrix a: 
[[1 2 3]
 [4 5 6]]
(2, 3)


Matrix b: 
[10 20]
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 